#!/bin/bash

# Script to display a sequence of number
# Closebox73

DATE=$(date +"%^d")

if [[ "${DATE}" = *01* ]] || [[ "${DATE}" = *21* ]] || [[ "${DATE}" = *31* ]]; then
    echo "ST"
elif [[ "${DATE}" = *02* ]] || [[ "${DATE}" = *22* ]]; then
    echo "ND"
elif [[ "${DATE}" = *03* ]] || [[ "${DATE}" = *23* ]]; then
    echo "RD"
else
	echo "TH"
fi

exit
